import Head from 'next/head'
import React from 'react'
import Header from '../components/Header'


export default function Home() {
  return (
    <>
      <Head>
        <title>AI IMAGE GENERATOR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
<Header/>
     
    </>
  )
}
